### ISSUE TITLE
G4/6 - Name, Role, Value - Expanded/Collapsed state needs to be communicated to screen readers

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#126]
The Global Nav will say the menu is collapsed, even if it is expanded. It also only says "menu" when you expand it.

The Local Nav doesn't say anything when you expand or collapse the menu.

**Comment by mmafe** [comment]
This appears to have to do with the version of BootstrapCDN that we're using.

Ours is linked to https://maxcdn.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js.

Expand/collapse state is only communicated (via aria-expanded) if we use version 3.3.5: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js.

To fix, I've added the 3.3.5 option to the bootstrapCDN UI settings file. This is almost identical to the following patch, only instead of adding multiple versions, I've just gone with the latest one: https://www.drupal.org/node/2538856

Once applied, you can switch to version 3.3.5 through Appearance / Settings / UG Cornerstone Theme

**Comment by mmafe** [comment]
Fixed in Hot Fix (Local Machine). Will be pushed to dev master this afternoon.

**Comment by jpinsent** [comment]
Testing with NVDA. Found a couple issues:

- NVDA is having trouble with the Local Nav when the page firsts loads. It's not picking up that menus are collapsed until the user expands and collapses it.
E.g. On page load, it reads "About CCS visited link". When expanded and then collapsed, it will from then on read, "About CCS collapsed visited link".

- For the Global Nav, when a menu is expanded, the screen reader says "Expanded. Menu expanded.", but when a menu is collapsed it says nothing. The Local Nav says nothing about the expanded/collapsed state of the menu upon button press.

**Comment by mmafe** [comment]
#1 NVDA is having trouble with the Local Nav when the page firsts loads. It's not picking up that menus are collapsed until the user expands and collapses it. E.g. On page load, it reads "About CCS visited link". When expanded and then collapsed, it will from then on read, "About CCS collapsed visited link".

**Fixed**
- Added aria-expanded=false to default state of dropdown menus (local nav)
- Added aria-popup=true to local nav dropdown togles to indicate there is a submenu associated with the dropdown menus

Applied in hotfix_20150807.2

**Comment by mmafe** [comment]
#2 For the Global Nav, when a menu is expanded, the screen reader says "Expanded. Menu expanded.", but when a menu is collapsed it says nothing. The Local Nav says nothing about the expanded/collapsed state of the menu upon button press.

**Not Fixed - More Testing Needed**
I attempted to fix this by include a sr-only "Show menu/Hide menu" that toggled between the two states. However, after listening to it on NVDA and Voiceover, I was hearing too many state indicators on NVDA.
For the moment, I've removed everything but the (essential) aria-expanded toggle. 

I'll create a new issue that can be added to the next Hotfix milestone.

**Changes**
- Removed aria-popup=true from local nav dropdown menus until we can do further testing

Applied in hotfix_20150807.2

**Comment by mmafe** [comment]
Currently this work in Firefox with NVDA. In Chrome, the state has been changed, but we do not hear the state unless we tab away from the toggle button and back onto it again. Since we've added the aria-expanded toggle behaviour, I'm considering this issue solved.

For issues related to Chrome and NVDA not announcing the toggle state as it's being changed, I've created a new issue: https://github.com/brharp/hjckrrh/issues/166
