### ISSUE TITLE
F3- FAQ category links

### ISSUE THREAD

**Issue by anncesar** [brharp/hjckrrh#140]
Please ensure FAQ category links are not underlined as per class="no-link-lines"

**Comment by mmafe** [comment]
Applied as part of hotfix_20150807.3.0.

Applied for FAQ, News, and Events

**Summary of Fix:** Added a new class called browse-by-list that can be applied to views such as Browse by Date, Browse by Category, etc. in order to avoid seeing an underline by default (underline appears on hover/focus).

**Note:** This change will only show up for default features (not overridden). If you'd like to apply it to overridden views, you can do this through Structure / Views. Select your view (which is preferably a view that only contains linked list items) and add "browse-by-list" as a class under Advanced / CSS Class.

**Comment by mmafe** [comment]
Confirmed. Showing up on AODA Demo (which is fully reverted)
