### ISSUE TITLE
Alt text needed in case of uploaded PDF 

### ISSUE THREAD

**Issue by Dmelady** [brharp/hjckrrh#159]
The icon represented contains no Alt text
![image](https://cloud.githubusercontent.com/assets/13487599/9332729/14b68620-4594-11e5-868e-2050a35db209.png)

Currently failing in SiteImprove

**Comment by mmafe** [comment]
This issue is also being tracked in https://github.com/brharp/hjckrrh/issues/121

**Comment by jpinsent** [comment]
Alt text is now identical to the title text. 

Is there any way we could improve the descriptive alt text, @mmafe? This issue is technically resolved, but some of the alt text is overtly long and none are formatted in a very screen-reader-friendly manner (e.g. the icon for the docx extension comes through as "application/vnd.openxmlformats-officedocument.wordprocessingml.document"). It would be nice if they were just something like "pdf", "zip", "docx", etc.

![attachment alt](https://cloud.githubusercontent.com/assets/12450480/9587476/bb607d4e-4ff0-11e5-86fc-d280fea59eab.PNG)

**Comment by mmafe** [comment]
At a glance, it looks like the file module we're using appears to only have access to the mimetype when generating the icon.

For now, I'd suggest closing this issue if it solves the issue and creating a new (low priority) issue specific to the alternative text wording to see if we can improve it going forward.
