### ISSUE TITLE
N6 - News Topics doesn't link correctly

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#184]
When you click on a news topic on the bottom right of a news article, it takes you to a FAQ catagory.

![news 1](https://cloud.githubusercontent.com/assets/12450523/9498269/e0472986-4be6-11e5-9719-182cbf332fc2.PNG)

![news 2](https://cloud.githubusercontent.com/assets/12450523/9498271/e136b42e-4be6-11e5-9f71-1486e5757836.PNG)

**Comment by mmafe** [comment]
Getting a 404 on aodademo when linking to /news/category. Investigating.

**Comment by mmafe** [comment]
Since taxonomy terms all have different ids on each new site, the context for the page ends up matching to a different id (i.e. faq on AODA, sub-unit on OAC, etc.) For now, I'm just going to remove the specific vocabulary limit set through Pages. The view already limits the argument to News and generates a working URL, so it should still work.

**Comment by mmafe** [comment]
Ready for testing

**Comment by jpinsent** [comment]
Tested on AODA Demo and it looks like it is now working as intended.
