### ISSUE TITLE
G0 - Disabled Bootstrap buttons can still be accessed

### ISSUE THREAD

**Issue by jpinsent** [brharp/hjckrrh#72]
Bootstrap buttons with the 'disabled' class cannot be clicked, but can still be accessed if navigated to by keyboard. They also appear as fully-clickable links if CSS is disabled.

![button bug 1](https://cloud.githubusercontent.com/assets/12450480/8361910/ceb8c144-1b43-11e5-8e91-d3f21d5e348d.PNG)
![button bug 2](https://cloud.githubusercontent.com/assets/12450480/8361914/d2ed9ed8-1b43-11e5-8fe0-cb0b90c8549a.PNG)

**Comment by mmafe** [comment]
Bootstrap allows you to use the button classes on both links and buttons. We'll just need to make sure that when a button's meant to act as a button, we select <button> instead of <a>. For the stylesheet, I've switched them all the buttons and added a disabled attribute to the disabled ones. 

![image](https://cloud.githubusercontent.com/assets/1927902/8386052/246d3570-1c1b-11e5-88be-f10477de9680.png)
