### ISSUE TITLE
FT3 - Can't sort by category (eg. featured videos)

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#94]
If you try to sort the view by the feature categories in taxonomy, no featured items show up on the view.

**Comment by jszasz** [comment]
The sort works with the taxonomy ID not the name of it.

**Comment by brharp** [comment]
I have changed the feature category filter to accept a name instead of a term id.

**Comment by mmafe** [comment]
**Update:** @brharp  and I were chatting recently, and we're thinking it'll be wiser to switch to term id's when it comes to any category filtering with views. Site managers can be made aware that it's the number they need to input in the in-place-editor, not the term name. 

**Huge benefit:** If they need to change the label of the term, they don't need to go back through all the views and update the name since the ID# stays consistent.

**Comment by mancusop** [comment]
If you guys do this let me know and I can then add it to my taxonomies with regard to creating links via terms. (I believe this is how I am supposed to interpret it?)

**Comment by mmafe** [comment]
@mancusop We are doing this -- in some cases, it may already be done. If you see cases where the term name is being used to filter, please create an issue so we can fix.
